macro_rules! server_prot {
    ( $( $variant:ident = $id:expr ),* $(,)? ) => {
        #[repr(u8)]
        #[derive(Debug)]
        pub enum ServerProt {
            $( $variant = $id, )*
        }
    };
}

#[cfg(rev = "225")]
server_prot! {
    NpcInfo = 1, // NXT naming
    IfSetColour = 2, // NXT naming
    CamMoveTo = 3, // NXT naming
    MessageGame = 4, // NXT naming
    UpdateZonePartialFollows = 7, // NXT naming
    SynthSound = 12, // NXT naming
    CamShake = 13, // NXT naming
    IfOpenChat = 14,
    UpdateInvStopTransmit = 15, // NXT naming
    UnsetMapFlag = 19, // NXT has "SET_MAP_FLAG" but we cannot control the position
    DataLocDone = 20,
    UpdateIgnoreList = 21, // NXT naming
    UpdateRunWeight = 22, // NXT naming
    LocMerge = 23,
    HintArrow = 25, // NXT naming
    IfSetHide = 26, // NXT naming
    IfOpenMainSide = 28,
    ChatFilterSettings = 32, // NXT naming
    MessagePrivate = 41, // NXT naming
    LocAnim = 42,
    UpdateRebootTimer = 43, // NXT naming
    UpdateStat = 44, // NXT naming
    IfSetObject = 46, // NXT naming
    ObjDel = 49,
    ObjReveal = 50,
    MidiSong = 54, // NXT naming
    LocAddChange = 59,
    UpdateRunEnergy = 68, // NXT naming
    MapProjAnim = 69,
    CamLookAt = 74, // NXT naming
    LocDel = 76,
    DataLandDone = 80,
    IfSetTabActive = 84,
    IfSetModel = 87, // NXT naming
    UpdateInvFull = 98, // NXT naming
    TutFlash = 126,
    IfClose = 129,
    IfSetRecol = 103, // NXT naming
    DataLand = 132,
    FinishTracking = 133,
    UpdateZoneFullFollows = 135, // NXT naming
    ResetAnims = 136, // NXT naming
    UpdatePid = 139,
    LastLoginInfo = 140, // NXT naming
    Logout = 142, // NXT naming
    IfSetAnim = 146, // NXT naming
    VarpSmall = 150, // NXT naming
    ObjCount = 151,
    UpdateFriendList = 152, // NXT naming
    UpdateZonePartialEnclosed = 162, // NXT naming
    IfSetTab = 167,
    IfOpenMain = 168,
    VarpLarge = 175, // NXT naming
    PlayerInfo = 184, // NXT naming
    TutOpen = 185,
    MapAnim = 191,
    ResetClientVarCache = 193, // NXT naming
    IfOpenSide = 195,
    IfSetPlayerHead = 197, // NXT naming
    IfSetText = 201, // NXT naming
    IfSetNpcHead = 204, // NXT naming
    IfSetPosition = 209, // NXT naming
    MidiJingle = 212, // NXT naming
    UpdateInvPartial = 213, // NXT naming
    DataLoc = 220,
    ObjAdd = 223,
    EnableTracking = 226,
    RebuildNormal = 237, // NXT naming (do we really need _normal if there's no region rebuild?)
    CamReset = 239, // NXT naming
    PCountDialog = 243, // named after runescript command + client resume_p_countdialog packet
    SetMultiway = 254,
}

#[cfg(rev = "244")]
server_prot! {
    UpdateIgnoreList = 7,
    ChatFilterSettings = 9,
    IfOpenMain = 10,
    CamMoveTo = 12,
    Logout = 17,
    EnableTracking = 22,
    UpdateStat = 24,
    LocMerge = 29,
    MessagePrivate = 30,
    ObjDel = 39,
    LastLoginInfo = 44,
    HintArrow = 49,
    CamShake = 50,
    CamReset = 53,
    IfSetTabActive = 56,
    FinishTracking = 60,
    UnsetMapFlag = 62,
    ObjReveal = 69,
    UpdateFriendList = 70,
    UpdateInvFull = 72,
    IfSetColour = 78,
    UpdateRebootTimer = 85,
    PlayerInfo = 86,
    ResetClientVarCache = 87,
    UpdateZonePartialFollows = 94,
    MessageGame = 95,
    SetMultiway = 97,
    IfSetRecol = 103,
    IfSetPlayerHead = 108,
    IfOpenOverlay = 158,
    IfSetHide = 123,
    LocDel = 125,
    IfSetNpcHead = 129,
    UpdateZoneFullFollows = 131,
    UpdateInvPartial = 132,
    MapProjAnim = 137,
    SynthSound = 151,
    PCountDialog = 152,
    IfSetText = 154,
    LocAnim = 155,
    UpdateRunWeight = 160,
    UpdateInvStopTransmit = 162,
    IfSetObject = 164,
    RebuildNormal = 165,
    TutFlash = 168,
    MidiJingle = 173,
    TutOpen = 174,
    IfOpenSide = 176,
    UpdateRunEnergy = 177,
    IfOpenChat = 189,
    MapAnim = 198,
    IfSetTab = 200,
    IfOpenMainSide = 207,
    ObjCount = 209,
    UpdatePid = 210,
    IfClose = 214,
    IfSetAnim = 219,
    CamLookAt = 222,
    VarpLarge = 226,
    LocAddChange = 232,
    UpdateZonePartialEnclosed = 233,
    ObjAdd = 234,
    VarpSmall = 236,
    MidiSong = 240,
    IfSetPosition = 241,
    ResetAnims = 242,
    NpcInfo = 244,
    IfSetModel = 245,
}

#[cfg(rev = "245.2")]
server_prot! {
    ChatFilterSettings = 2, // NXT naming
    IfOpenChat = 7,
    IfSetTabActive = 8,
    ObjDel = 13,
    UpdateZonePartialEnclosed = 15, // NXT naming
    ResetClientVarCache = 25, // NXT naming
    UpdateRebootTimer = 26, // NXT naming
    EnableTracking = 28,
    IfSetTab = 29,
    IfSetText = 32, // NXT naming
    SetMultiway = 35,
    Logout = 36, // NXT naming
    MidiJingle = 39, // NXT naming
    UpdatePid = 49,
    PCountDialog = 56, // named after runescript command + client resume_p_countdialog packet
    IfSetModel = 60, // NXT naming
    RebuildNormal = 66, // NXT naming (do we really need _normal if there's no region rebuild?)
    IfSetAnim = 69, // NXT naming
    UpdateRunWeight = 70, // NXT naming
    LocAnim = 71,
    VarpLarge = 75, // NXT naming
    IfSetNpcHead = 76, // NXT naming
    IfSetPlayerHead = 83, // NXT naming
    CamMoveTo = 86, // NXT naming
    ObjAdd = 94,
    UpdateInvPartial = 95, // NXT naming
    MidiSong = 96, // NXT naming
    CamShake = 103, // NXT naming
    NpcInfo = 105, // NXT naming
    UpdateFriendList = 109, // NXT naming
    UpdateStat = 110, // NXT naming
    IfOpenOverlay = 115,
    LocAddChange = 119,
    CamLookAt = 123, // NXT naming
    TutFlash = 132,
    CamReset = 134, // NXT naming
    IfSetColour = 135, // NXT naming
    UpdateZoneFullFollows = 140, // NXT naming
    MapAnim = 141,
    UpdateInvStopTransmit = 143, // NXT naming
    ResetAnims = 144, // NXT naming
    ObjCount = 151,
    TutOpen = 152,
    IfSetObject = 153, // NXT naming
    UpdateInvFull = 156, // NXT naming
    PlayerInfo = 161, // NXT naming
    FinishTracking = 165,
    IfClose = 174,
    MessageGame = 175, // NXT naming
    IfOpenMain = 177,
    UpdateIgnoreList = 181, // NXT naming
    MapProjAnim = 187,
    LocMerge = 188,
    ObjReveal = 190,
    VarpSmall = 192, // NXT naming
    LocDel = 198,
    UpdateZonePartialFollows = 203, // NXT naming
    MessagePrivate = 207, // NXT naming
    UpdateRunEnergy = 208, // NXT naming
    SynthSound = 209, // NXT naming
    IfSetHide = 225, // NXT naming
    IfSetScrollPos = 226, // NXT naming
    IfOpenMainSide = 229,
    IfSetPosition = 230, // NXT naming
    UnsetMapFlag = 233, // NXT has "SET_MAP_FLAG" but we cannot control the position
    IfOpenSide = 236,
    LastLoginInfo = 238, // NXT naming
    HintArrow = 243, // NXT naming
}
