use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let mut table = [0; 99];
    let mut acc: i32 = 0;
    for level in 1..99 {
        acc += ((level as f64) + 2.0_f64.powf(level as f64 / 7.0) * 300.0).floor() as i32;
        table[level] = (acc / 4) * 10;
    }

    let mut entries = String::new();
    for (i, value) in table.iter().enumerate() {
        if i % 10 == 0 {
            entries.push_str("\n    ");
        }
        write!(entries, "{value}, ").expect("write entry");
    }

    let contents = format!(
        "// @generated by rs-stat/build.rs from the RuneScape XP curve -- do not edit.\n\
         /// Cumulative experience (stored at 10x real XP) required to reach each\n\
         /// level 1..=99 (index `i` maps to level `i + 1`). Strictly increasing,\n\
         /// so it can be binary-searched.\n\
         const LEVEL_XP: [i32; 99] = [{entries}\n];\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    fs::write(Path::new(&out_dir).join("level_xp.rs"), contents).expect("write level_xp.rs");
}
