[alias]
unpack = "run -p rs-pack -- unpack -e expected -o content_unpack"
verify = "run -p rs-pack -- verify -e expected -u content_unpack"

world1 = "run -p rs-server --release -- --node-id 10 --cluster world10@127.0.0.1,world11@127.0.0.1"
world2 = "run -p rs-server --release -- --node-id 11 --cluster world10@127.0.0.1,world11@127.0.0.1"

[env]
REV = "289"

[build]
target-dir = "target"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=/STACK:8388608"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true
overflow-checks = false

[profile.dev]
opt-level = 0
debug = 2

[profile.dev-opt]
inherits = "dev"
opt-level = 2
